### ISSUE TITLE
Error when no files to check

### ISSUE THREAD

**Issue by bernhold** [urlstechie/urlchecker-action#84] opened 2022-04-01 01:45 UTC
Great tool, thanks!

But it seems like it throws an error if there are no files to check.  Shouldn't it just quietly succeed in that case?

A little ugly, but here's a snip from the log file.

>urlchecker check  --branch master --no-print --file-types .md,.py,.rst,.html --exclude-urls [https://en.w,https://github.com/bssw-tutorial/presentations/blob/master,https://doi.org/10.1126/science.aah6168,https://doi.org/10.1002/spe.2220](https://en.w%2Chttps//github.com/bssw-tutorial/presentations/blob/master,https://doi.org/10.1126/science.aah6168,https://doi.org/10.1002/spe.2220) --retry-count 1 --timeout 5 --files .github/workflows/check-pr-urls.yml .
Traceback (most recent call last):
           original path: .
              final path: /github/workspace
               subfolder: None
                  branch: master
  File "/opt/conda/bin/urlchecker", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/urlchecker/client/__init__.py", line 191, in main
    main(args=args, extra=extra)
  File "/opt/conda/lib/python3.9/site-packages/urlchecker/client/check.py", line 83, in main
    check_results = checker.run(
  File "/opt/conda/lib/python3.9/site-packages/urlchecker/core/check.py", line 193, in run
    for file_name, result in results.items():
AttributeError: 'NoneType' object has no attribute 'items'
                 cleanup: False
              file types: ['.md', '.py', '.rst', '.html']
                   files: ['.github/workflows/check-pr-urls.yml']
               print all: False
                 verbose: False
           urls excluded: ['https://en.w', 'https://github.com/bssw-tutorial/presentations/blob/master', 'https://doi.org/10.1126/science.aah[61](https://github.com/bssw-tutorial/bssw-tutorial.github.io/runs/5781004510?check_suite_focus=true#step:5:61)[68](https://github.com/bssw-tutorial/bssw-tutorial.github.io/runs/5781004510?check_suite_focus=true#step:5:68)', 'https://doi.org/10.1002/spe.2220']
   url patterns excluded: []
  file patterns excluded: []
              force pass: False
             retry count: 1
                    save: None
                 timeout: 5

**Comment by vsoch** [comment] 2022-04-01 02:18
Yeah totally agree! So I think we first had it as a failure because one would expect there to be some URL to check (and if not you might have messed up the configuration.) Can you point me to the repo you were testing so I can double check the bug and put in a fix? Thank you!

**Comment by vsoch** [comment] 2022-04-01 02:20
Actually I just reproduced! Will have a fix shortly.

**Comment by vsoch** [comment] 2022-04-01 02:25
okay here you go! Take this for a spin https://github.com/urlstechie/urlchecker-python/pull/67. if that is good, when we merge and release there it will build a new base container for the action here.

**Comment by vsoch** [comment] 2022-04-01 03:35
Thank you @bernhold ! This is fixed, merged, both here and for urlchecker-python.

**Closed as completed by vsoch** 2022-04-01 03:35 UTC

**Comment by bernhold** [comment] 2022-04-01 14:56
Confirmed.  Thanks very much!
